FROM python:2.7

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY ./mqtt_services/logsensors.py /app
COPY ./example /app/

ENTRYPOINT ["python", "logsensors.py", "-c", "logsensors.yaml"]
CMD []
